name = "ITransverse"
uuid = "0b04ad49-86dd-4710-99cf-a56925ebcbe5"
authors = ["Stefano Carignano <stefano.carignano@fqa.ub.edu>"]
version = "0.1.0"

[deps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
