###############################################################################
#  Quantum numbers in the FOLDED transverse network (draft)
###############################################################################
#
# The folded tensors are WW = W ⊗ conj(W), with every leg of W fused with its conjugate
# partner. Without QNs that fusion is a `combiner` (ket index fastest, the "Kronecker
# order" n = a + d(b-1)), and boundary vectors such as `rho0` or `fold_op = [1,0,0,-1]` are
# written in that order.
#
# With QNs a leg x and its partner dag(x'') fuse into one index F whose states carry the
# charge q(a) - q(b), grouped into blocks. Two things have to hold for the folded network to
# contract:
#
#  * the SAME fusion for a leg wherever it appears: the spatial link between sites 1 and 2
#    is an outgoing leg of W_l and an incoming one of W_c, and both become the same time
#    site of the rotated column. A `combiner` gives no such guarantee once arrows differ, so
#    the fusion here is explicit: the layout of F (block order and the state order inside a
#    block) is a function of the stored QNs of x only (`_qn_fold_layout`), and the arrow of
#    F is that of x;
#  * boundary vectors in the fused basis. They are still GIVEN in Kronecker order (the same
#    vectors as without QNs) and permuted by the builders (`_qn_fold_boundary`), so the user
#    side does not change. Only product boundaries are supported with QNs for now.
#
# The charge of a fused state, q(a) - q(b), is the difference of the ket and bra charges:
# folding keeps the symmetry of ρ ↦ U ρ U† generated by P ⊗ P̄, i.e. one Z2 per fold for
# `conserve_szparity` (the separate ket and bra charges are not kept).

""" Fused layout of `x ⊗ conj(x)`: QN space (blocks in order of first appearance) and
`perm[k]` = Kronecker position `a + d(b-1)` of fused state `k`. Depends only on the stored
QNs of `x`, not on its arrow. """
function _qn_fold_layout(x::Index)
    d = dim(x)
    qs = [qn(x, a) for a in 1:d]
    f = [qs[a] - qs[b] for b in 1:d for a in 1:d]          # a fastest
    reps = unique(f)
    perm = reduce(vcat, [findall(==(q), f) for q in reps])
    space = [q => count(==(q), f) for q in reps]
    return space, perm
end

""" Fusion tensor of the stored leg `x` of W with its partner `prime(x, 2)` of dag(W''),
into `F` (whose arrow is set to that of `x`). Entry 1 at (a, b, k) with perm[k] = a + d(b-1). """
function _qn_fuser(x::Index, F::Index)
    d = dim(x)
    _, perm = _qn_fold_layout(x)
    Fx = ITensors.setdir(F, dir(x))
    T = ITensor(Float64, dag(x), prime(x, 2), Fx)
    for (k, n) in enumerate(perm)
        a, b = mod1(n, d), div(n - 1, d) + 1
        T[dag(x) => a, prime(x, 2) => b, Fx => k] = 1.0
    end
    return T
end

""" `W ⊗ dag(W'')` with each leg in `legs` (as stored in W) fused into its target index. """
function _qn_fold_tensor(W::ITensor, legs_targets)
    WW = W * dag(prime(W, 2))
    for (leg, F) in legs_targets
        WW = WW * _qn_fuser(stored_ind(W, leg), F)
    end
    return WW
end

""" QN counterpart of `build_WW(::MPO)`: same outputs, legs fused by `_qn_fuser`. """
function _build_WW_qn(eH::MPO)
    length(eH) == 3 || error("build_WW with QNs expects the 3-site MPO (left edge, bulk, right edge)")
    l1, l2 = linkinds(eH)
    s = [siteind(eH, j) for j in 1:3]
    all(j -> space(s[j]) == space(s[2]), 1:3) ||
        error("build_WW with QNs: the three site indices must have the same QN space")
    space(l1) == space(l2) ||
        error("build_WW with QNs: the two links of the 3-site MPO must have the same QN space")

    lspace, _ = _qn_fold_layout(l1)
    pspace, _ = _qn_fold_layout(s[2])
    space_link1 = Index(lspace, "Link,space")
    space_link2 = Index(lspace, "Link,space")
    space_phys  = Index(pspace, "Site,space")

    phys(j) = (s[j] => space_phys, s[j]' => space_phys')
    WWl = _qn_fold_tensor(eH[1], (phys(1)..., l1 => space_link1))
    WWc = _qn_fold_tensor(eH[2], (phys(2)..., l1 => space_link1, l2 => space_link2))
    WWr = _qn_fold_tensor(eH[3], (phys(3)..., l2 => space_link2))

    return WWl, WWc, WWr, (space_link1, space_link2, space_phys, space_phys')
end

"""
    _replaceinds_arrow(T, olds, news)

`replaceinds` that keeps the arrow of every replaced leg as stored in `T` (legs not in `T`
are skipped, as `replaceinds` does). Plain `replaceinds` without QNs.
"""
function _replaceinds_arrow(T::ITensor, olds, news)
    hasqns(T) || return replaceinds(T, olds, news)
    for (o, n) in zip(olds, news)
        any(x -> id(x) == id(o) && plev(x) == plev(o), inds(T)) || continue
        x = stored_ind(T, o)
        T = replaceind(T, x => ITensors.setdir(n, dir(x)))
    end
    return T
end

""" Kronecker → fused permutation of the folded time links of `b` (`nothing` without QNs). """
function _qn_fold_perm(b)
    hasqns(b.iR) || return nothing
    s = b.tp.mp.phys_site
    hasqns(s) || error("folded QN blocks: tp.mp.phys_site carries no QNs, cannot recover the fused basis")
    return last(_qn_fold_layout(s))
end

"""
    _qn_fold_boundary(b, x, hook)

A product boundary of the folded network (`rho0`, `fold_op`), given in Kronecker order as without
QNs, moved to the fused basis of the QN time link `hook`. `nothing` means the vectorized identity.
Returns `x` unchanged without QNs.
"""
function _qn_fold_boundary(b, x, hook::Index)
    perm = _qn_fold_perm(b)
    if perm === nothing
        return something(x, vectorized_identity(hook))
    end
    d2 = dim(hook)
    v = if x === nothing
        vectorized_identity(d2)
    elseif x isa AbstractVector
        x
    elseif x isa ITensor && ndims(x) == 1 && !hasqns(x)
        Array(adapt(Array, x), ind(x, 1))  # may live on GPU (togpu(b)); attach_* moves it back
    else
        error("""
            folded network with QNs: boundaries must be product states given as a Vector (or a
            1-leg QN-free ITensor) in the Kronecker order used without QNs. Non-product
            boundaries are not supported with QNs yet.""")
    end
    length(v) == d2 || error("folded boundary of length $(length(v)), the time link has dimension $(d2)")
    return complex(collect(v))[perm]
end

"""
    folded_time_sites(b::FoldtMPOBlocks, Nt) -> Vector{Index}

Time sites for a folded column of `Nt` sites: copies of `b.iP` (QNs kept). With QNs the time
sites must carry the fused QN space of `b.iP`; without QNs this is the same as plain indices
of dimension `dim(b.iP)`.
"""
folded_time_sites(b::FoldtMPOBlocks, Nt::Int) = [sim(b.iP; tags = "Site,time,t=$ii") for ii in 1:Nt]

function _check_qn_time_sites(b, ts)
    hasqns(b.iP) || return nothing
    all(t -> hasqns(t) && space(t) == space(b.iP), ts) || error("""
        folded QN blocks: the time sites must carry the fused QN space of b.iP; build them with
        `folded_time_sites(b, Nt)` (or `sim(b.iP)`).""")
    return nothing
end
